version: '3.9'

services:

  library-api:
    container_name: library-api

    build:
      context: ./LibraryManagementApi.API

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=LibraryManagementDb;User=sa;Password=Your_password123;TrustServerCertificate=True"

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: sqlserver

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: